import "@/styles/globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { PostHogProvider } from "./_providers/posthog-provider";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
  title: "Create K11 drive",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
     <ClerkProvider>
      <html lang="en" className={`${geist.variable}`}>
      <body> <PostHogProvider>{children}</PostHogProvider></body> 
      </html>
     </ClerkProvider>
  );
}
